/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d2ddd7',
        'on-secondary-fixed-variant': '#214f41',
        'error-container': '#ffdad6',
        'primary-container': '#005f41',
        'on-surface': '#141e1a',
        'on-error': '#ffffff',
        'outline': '#6f7a73',
        'surface-container-low': '#ebf6f0',
        'surface-container-highest': '#dae5df',
        'inverse-on-surface': '#e8f3ed',
        'outline-variant': '#bec9c1',
        'on-primary-container': '#89d6b0',
        'secondary': '#3a6758',
        'on-surface-variant': '#3f4943',
        'surface-container-high': '#e0ebe5',
        'tertiary-container': '#49564f',
        'on-error-container': '#93000a',
        'inverse-surface': '#29332f',
        'surface-variant': '#dae5df',
        'surface': '#f1fcf6',
        'surface-bright': '#f1fcf6',
        'secondary-container': '#bcedda',
        'background': '#f1fcf6',
        'on-secondary-container': '#002118',
        'on-background': '#141e1a',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#a4f3cb',
        'inverse-primary': '#89d6b0',
        'secondary-fixed': '#bcedda',
        'primary': '#00452e',
        'on-tertiary': '#ffffff',
        'surface-container': '#e5f0ea',
        'tertiary': '#323f38',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'error': '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        sm: '12px',
        'container-margin': '20px',
        base: '4px',
        gutter: '16px',
        xs: '8px',
        lg: '24px',
        md: '16px',
        xl: '32px',
      },
      fontFamily: {
        'label-caps': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-sm': ['Manrope'],
        'headline-lg-mobile': ['Manrope'],
        'headline-md': ['Manrope'],
        'headline-lg': ['Manrope'],
      },
      fontSize: {
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
