version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  evolution:
    image: atendai/evolution-api:v2.1.1
    ports:
      - "8080:8080"
    environment:
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://postgres:postgres@postgres:5432/evolution
      AUTHENTICATION_API_KEY: soromais123
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://redis:6379
    depends_on:
      - postgres
      - redis
